#include "WorldChunk.h"
#include "WorldObject.h"
#include "Powerup.h"

class World_1
{
public:
	World_1(Ogre::SceneManager *mSceneMgr, std::list<Object *> &objectList, std::list<Powerup *> &powerUpList);
	WorldObject *Start;
	Powerup *Powerup1;
	Powerup *Powerup2;
	
	WorldObject *Rock1;
	WorldObject *Rock2;
	WorldObject *Rock3;
	WorldObject *Rock4;
	WorldObject *Rock5;
	WorldObject *Rock6;
	WorldObject *Rock7;
	WorldObject *Rock8;
	WorldObject *Rock9;
	WorldObject *Rock10;
	WorldObject *Rock11;
	WorldObject *Rock12;
	WorldObject *Rock13;
	WorldObject *Rock14;
	WorldObject *Rock15;
	WorldObject *Rock16;
	WorldObject *Rock17;
	WorldObject *Rock18;

	WorldObject *Struc1;

	WorldObject *Rock19;
	WorldObject *Rock20;
	WorldObject *Rock21;
	WorldObject *Rock22;
	WorldObject *Rock23;
	WorldObject *Rock24;
	WorldObject *Rock25;
	WorldObject *Rock26;
	WorldObject *Rock27;
	WorldObject *Rock28;
	WorldObject *Rock29;
	WorldObject *Rock30;
	WorldObject *Rock31;
	WorldObject *Rock32;
	WorldObject *Rock33;
	WorldObject *Rock34;
	WorldObject *Rock35;
	WorldObject *Rock36;
	WorldObject *Rock37;
	WorldObject *Rock38;
	WorldObject *Rock39;
	WorldObject *Rock40;
	WorldObject *Rock41;
	WorldObject *Rock42;
	WorldObject *Rock43;
	WorldObject *Rock44;
	WorldObject *Rock45;
	WorldObject *Rock46;
	WorldObject *Rock47;
	WorldObject *Rock48;
	WorldObject *Rock49;
	WorldObject *Rock50;
	WorldObject *Rock51;
	WorldObject *Rock52;
	WorldObject *Rock53;
	WorldObject *Rock54;
	WorldObject *Rock55;
	WorldObject *Rock56;
	WorldObject *Rock57;
	WorldObject *Rock58;
	WorldObject *Rock59;
	WorldObject *Rock60;
	WorldObject *Rock61;
	WorldObject *Rock62;
	WorldObject *Rock63;
	WorldObject *Rock64;
	WorldObject *Rock65;
	WorldObject *Rock66;
	WorldObject *Rock67;
	WorldObject *Rock68;
	WorldObject *Rock69;
	WorldObject *Rock70;
	WorldObject *Rock71;
	WorldObject *Rock72;
	WorldObject *Rock73;
	WorldObject *Rock74;
	WorldObject *Rock75;
	WorldObject *Rock76;
	WorldObject *Rock77;
	WorldObject *Rock78;
	WorldObject *Rock79;
	WorldObject *Rock80;
	WorldObject *Rock81;
	WorldObject *Rock82;
	WorldObject *Rock83;
	WorldObject *Rock84;
	WorldObject *Rock85;
	WorldObject *Rock86;
	WorldObject *Rock87;
};